AWSTemplateFormatVersion: 2010-09-09
Description: create a template of vpc and subnet

# Metadata:

Parameters: 
  PJPrefix:
    Type: "String"
  SSHLocation: 
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: "0.0.0.0/0"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "must be a valid IP CIDR range of the form: x.x.x.x/x"
  AZPrimary:
    Description: "select primary-availability-zone"
    Type: AWS::EC2::AvailabilityZone::Name
  AZSecondary:
    Description: "select secondary-availability-zone"
    Type: AWS::EC2::AvailabilityZone::Name

# Mappings: 

# Conditions: 

Resources: 
# ----------------------
# VPC 
# internetgateway
# ----------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      "EnableDnsHostnames": True
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-vpc"
  internetgateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-ig"
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref "VPC"
      InternetGatewayId: !Ref internetgateway
# ----------------------
# subnet
# ----------------------
  Public1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZPrimary
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-public1-subnet"
  Public2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZSecondary
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-public2-subnet"
  Private1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZPrimary
      VpcId: !Ref VPC
      CidrBlock: 10.0.10.0/24
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-private2-subnet"
  Private2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZSecondary
      VpcId: !Ref VPC
      CidrBlock: 10.0.20.0/24
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-private2-subnet"
# ----------------------
# route-table
# routing
# ----------------------
  PulicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-public-route-table"
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${PJPrefix}-private-route-table"

  PublicRouting:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PulicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref internetgateway
# ----------------------
# routetable associate routing
# ----------------------
  Public1SubnetAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Public1
      RouteTableId: !Ref PublicRouteTable
  Public2SubnetAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Public2
      RouteTableId: !Ref PublicRoutetable
      
# Outputs:
  VpcOutput:
    Value: !Ref VPC
    Export:
      Name: VpcFromA
  Prefix: 
    Value: !Ref PJPrefix
    Export:
      Name: Prefix