AWSTemplateFormatVersion: 2010-09-09

Description: this is the template of cloudfornt

Parameters: 
  NetworkStackName:
    Description: The name of the CloudFormation stack you created for network resources.
    Type: String
    Default: test
    AllowedPattern: ^[a-zA-Z]{1}[a-zA-Z0-9-]*$
    MaxLength: 128
    MinLength: 1

Resources: 
  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig: 
        Origins: 
          - ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig: 
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: "http-only"
              OriginReadTimeout: 30
              OriginSSLProtocols: 
                - "TLSv1.2"
            # for template to associate origin with loadbalancer
            DomainName: !ImportValue 
              Fn::Sub: ${NetworkStackName}-LoadBalancer
            Id: !ImportValue 
              Fn::Sub: ${NetworkStackName}-LoadBalancer
            OriginPath: ""
        DefaultCacheBehavior: 
          AllowedMethods: 
            - "HEAD"
            - "GET"
          CachedMethods: 
            - "HEAD"
            - "GET"
          Compress: true
          # CachingOptimized
          CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6"
          SmoothStreaming: false
          TargetOriginId: !ImportValue 
            Fn::Sub: ${NetworkStackName}-LoadBalancer
          ViewerProtocolPolicy: "allow-all"
        PriceClass: "PriceClass_All"
        Enabled: true
        #ViewerCertificate: 
          #CloudFrontDefaultCertificate: True
          #MinimumProtocolVersion: "TLSv1"
          #SslSupportMethod: "vip"
        Restrictions: 
          GeoRestriction: 
            RestrictionType: "none"
        HttpVersion: "http2"
        DefaultRootObject: ""
        IPV6Enabled: true
      Tags:
        - Key: Name
          Value: !Sub ${NetworkStackName}-CloudFront
Outputs:
  DnsName:
    Description: the DNS Name of cloudfront
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export: 
      Name: !Sub ${NetworkStackName}-Cloudfront